### ISSUE TITLE
Netlify Deployment and git best-practices

### ISSUE THREAD

**Issue by egardner** [thegetty/quire-docs#182]
Hi Quire team!

I will be helping the SJMA with their Quire publication as a contractor over the next several months – it's nice to be back in the digital publishing world. I'm very impressed with all the progress Quire has made in the last 2 years. In case it is helpful, I thought I would start filing issues that I encounter in trying to use this tool as an end-user now.

My first question: **is it considered a "best practice" here to commit build artifacts (the JS/CSS files output by webpack, as well as the HTML files built by Hugo) to source control**? I'm curious how you've approached this in the projects under way thus far.

The current output of `quire new` does seem to include the contents of the `site` folder in the repo (there are some automated commits there, the last one happened a few months ago). At the same time, the `.gitignore` for the starter project includes both `public` and `site` – so it looks like the files inside of the `site` folder were force-committed (overriding the `.gitignore` list).

I assume the answer to this question is "it depends", because it will effect how the site is deployed.

Ideally, I'd love to 1) keep built files out of git history and 2) have Netlify automatically build *everything* (site and theme) when there is a commit to the `master` branch. But in practice it seems like getting both of these things is going to be tricky.

The closest I've been able to come to this has been to do the following (in a newly-created Quire project starting from `quire new`):
1. Remove the built files from the project: `git rm --cached -r site/`
2. Publish the repo to GitHub and added it to Netlify
3. Use the following for build settings within Netlify:
  - Base directory: `themes/quire-starter-theme`
  - Build command: `npm run build:production`
  - Publish directory: `../../site`

Setting "Base directory" is useful because this gives Netlify access to the theme's `package.json` files so that it can download and install the theme dependencies. And since Netlify can't actually run `quire build` (since that command lives in a private repo), this seems like the best way to ensure that the server build is identical to what is generated locally.

The only downside with this approach is that content-only changes that don't touch the theme files will no longer automatically trigger a build. This is because Netlify is only comparing the "base directory" (the theme subfolder), and seeing no change there bails early. The work-around is that you can force a build by manually triggering a deploy with the "Clear cache and rebuild site" option in the Netlify deploy dashboard. This is ok but not ideal.

An alternate approach would be to just run `hugo` in the top directory in Netlify (without making any attempt to build webpack assets), and publish from the `site` folder. The `site` files could probably continue being ignored in git, since they'd be built by Hugo on every commit, but you'd need to commit the CSS & JS files from webpack in the theme repo. This approach would work well if the theme was a separate submodule (changing the theme would mean bumping the submodule to a different commit, which would trigger a new `hugo` build) – I imagine this approach is closer to "the Hugo way™️", if such a thing exists.

Anyway, I'm curious if you all currently have a preferred way of doing these things. If so, it might be good to add some additional info to the docs and/or to change the `.gitignore` settings in the starter project and its theme.

**Comment by naeluh** [comment]
Hi Eric hope you are doing great! 

You are correct in most of your assumptions. 

We have some documentation for building sites on Netlify [here](https://gettypubs.github.io/quire/guide/netlify/).

A good start is these 3 things 

1. Adding a `netlify.toml` file

```toml
# netlify.toml
# The prefix is the path to your package.json file in your theme
# Change the path of your theme if it is not themes/quire-starter-theme.

# This section is the production configuration and is all you need to deploy
[build]
publish = "public"
command = "npm --prefix themes/quire-starter-theme run build:netlify"

[context.production.environment]
HUGO_VERSION = "0.55.4"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# These next configurations are optional

# This section is the pull request configuration
[context.deploy-preview]
command = "npm --prefix themes/quire-starter-theme run build:netlify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.4"

# This section is the branch configuration
[context.branch-deploy]
command = "npm --prefix themes/quire-starter-theme run build:netlify"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55.4"

# This section is the branch configuration but targets a specific branch and also runs a different command
[context.stage]
command = "npm --prefix themes/quire-starter-theme run build:stage"

[context.stage.environment]
HUGO_VERSION = "0.55.5"
```
Modify `netlify.toml` to work with your HUGO site `publish = "public"` is going to be your build directory and the `npm` script uses a `prefix` to find the path to the `package.json`

2. In your package.json file you can write a script like this 

```json
  "scripts": {
     "build": "webpack --config webpack/webpack.config.prod.js && cd ../../ && hugo --minify --config config.yml,config/site.yml"
  },
```
What this script will do is run `webpack` to build assets and then `hugo` to build the site. 

3. Add this to `site.yml`

```yml
baseURL: "https://www.example.com/whatever-url-here-or-nothing/"
canonifyURLs: true
```

This is the workflow we've been using but if you have any questions or suggestions I'd be happy to check it or help in any way. 

Thanks!

Nick
