### ISSUE TITLE
Update V1 Docs with Config.yaml info

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire-docs#598]
### Before proceeding, check to make sure there isn’t an existing issue for your suggestion or a similar one.

- [X] I have searched the existing issues and determined this is new suggestion.

### Idea being proposed

Many of the sections are not completed because we still need to confirm certain `config.yaml` information. 

@geealbers Are the configuration attributes listed in the "Supporting Information" section final? (These were pulled from the `feature/11ty` branch: `quire/packages/11ty/content/_data/config.yaml`) 

### What contribution category does your proposal fall under?

Other

### Supporting Information

```
analytics:
  googleId: ''

bylineFormat: name-title # name | name-title | false

bibliography:
  displayOnPage: true
  displayShort: true
  heading: Bibliography

citations:
  divider: ', '
  popupStyle: text # text | icon

entryPage:
  sideBySide: false
  objectLinkText: View in Collection

epub:
  defaultCoverImage: 'https://user-images.githubusercontent.com/7796401/39769476-29929fe4-52a1-11e8-85ac-ff41505b3d4c.png'
  outputDir: '_epub'

footnotes:
  backlinkSymbol: '↩'

figures:
  enableModal: true
  imageDir: '/_assets/images'

licenseIcons: true

localization:
  defaultLocale: en-us

menuType: full # full | brief

navigation:
  nextButtonText: Next
  prevButtonText: Back

pageTitle:
  labelDivider: '. '

searchEnabled: true

tableOfContents:
  contributorDivider: ' — '
```
